# Generated by Django 2.2.2 on 2019-06-09 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='webside',
            new_name='website',
        ),
    ]
